## CE

In [1]:
import torch.nn as nn
import torch

loss = nn.CrossEntropyLoss()

In [2]:
input = torch.Tensor([[0.81, -0.65, 0.07]])
target = torch.Tensor([0]).long()

print(input)
print(target)

print(input.shape)
print(target.shape)

tensor([[ 0.8100, -0.6500,  0.0700]])
tensor([0])
torch.Size([1, 3])
torch.Size([1])


In [3]:
output = loss(input, target)
print(output)

tensor(0.5361)


## Average of CE

In [25]:
input = torch.Tensor([[0.81, 0 ],
                      [-0.65, 0],
                      [0.07, 1]])
input = input.reshape(1, 3, 2)

target = torch.Tensor([[0, 2]]).long()

print(input.shape)
print(target.shape)

torch.Size([1, 3, 2])
torch.Size([1, 2])


In [27]:
loss = nn.CrossEntropyLoss(reduce=False)
output = loss(input, target)
print(output)

tensor([[0.5361, 0.5514]])


In [28]:
import numpy as np

data = np.array([0.81, -0.65, 0.07])
prob = np.e**data / np.sum(np.e**data)
prob

array([0.58501763, 0.13586232, 0.27912005])

In [29]:
-np.log(0.58501763)

0.5361132954522467

In [30]:
import numpy as np

data = np.array([0, 0, 1])
prob = np.e**data / np.sum(np.e**data)
prob

array([0.21194156, 0.21194156, 0.57611688])

In [31]:
-np.log(0.57611688)

0.5514447222043812